[workspace.package]
version = "1.0.0"

[workspace]
members = [ 
  "crates/apis",
  "crates/app",
  "crates/core",
]
resolver = "2"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.dependencies]
serde = "1.0.209"
