[env] ## tells cargo make that we're in the context of a Cargo workspace
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config] ## we want most/all of our tasks to run in the context of a workspace
default_to_workspace = false

[tasks.run]
command = "cargo"
args = ["run"]

[tasks.release]
command = "cargo"
args = ["build", "--release"]
